# docker-compose.yml
version: '3.8'  # Use an appropriate version if needed

services:
  backend:
    image: kunjd26/ipdr-backend-app:v0  # Use your pre-built image name and tag
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: kunjd26/ipdr-frontend-app:v0  # Use your pre-built image name and tag
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - APP_ENV=development
      - APP_PORT=3000
      - APP_HOST=http://127.0.0.1
      - SERVER_PORT=5000
      - SERVER_HOST=http://backend

networks:
  app-network:
    driver: bridge
